sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
  - "7"
  - "8"

services:
  - docker

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

install:
  - npm install

before_install:
  - ./scripts/start-server.sh

script: make tests
